version: 2.1

jobs:
  job_1:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 1
          command: |
            echo "This is job 1"

  job_2:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 2
          command: |
            echo "This is job 2"

  job_3:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 3
          command: |
            echo "This is job 3"

  job_4:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 4
          command: |
            echo "This is job 4"

  job_5:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 5
          command: |
            echo "This is job 5"

  job_6:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 6
          command: |
            echo "This is job 6"

  job_7:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 7
          command: |
            echo "This is job 7"

  job_8:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 8
          command: |
            echo "This is job 8"

  job_9:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 9
          command: |
            echo "This is job 9"

  job_10:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 10
          command: |
            echo "This is job 10"

  job_11:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 11
          command: |
            echo "This is job 11"

  job_12:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 12
          command: |
            echo "This is job 12"

  job_13:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 13
          command: |
            echo "This is job 13"

  job_14:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 14
          command: |
            echo "This is job 14"

  job_15:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 15
          command: |
            echo "This is job 15"

  job_16:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 16
          command: |
            echo "This is job 16"

  job_17:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 17
          command: |
            echo "This is job 17"

  job_18:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 18
          command: |
            echo "This is job 18"

  job_19:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 19
          command: |
            echo "This is job 19"

  job_20:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 20
          command: |
            echo "This is job 20"

  job_21:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 21
          command: |
            echo "This is job 21"

  job_22:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 22
          command: |
            echo "This is job 22"

  job_23:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 23
          command: |
            echo "This is job 23"

  job_24:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 24
          command: |
            echo "This is job 24"

  job_25:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 25
          command: |
            echo "This is job 25"

  job_26:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 26
          command: |
            echo "This is job 26"

  job_27:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 27
          command: |
            echo "This is job 27"

  job_28:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 28
          command: |
            echo "This is job 28"

  job_29:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 29
          command: |
            echo "This is job 29"

  job_30:
    docker:
      - image: ngthvan1612/service_vocabulary_crawler:v1
    steps:
      - run:
          name: Job 30
          command: |
            echo "This is job 30"

workflows:
  version: 2
  workflow:
    jobs:
      - job_1
      - job_2
      - job_3
      - job_4
      - job_5
      - job_6
      - job_7
      - job_8
      - job_9
      - job_10
      - job_11
      - job_12
      - job_13
      - job_14
      - job_15
      - job_16
      - job_17
      - job_18
      - job_19
      - job_20
      - job_21
      - job_22
      - job_23
      - job_24
      - job_25
      - job_26
      - job_27
      - job_28
      - job_29
      - job_30
