version: 2.1
 
jobs:     
  job_1:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 1
          command: |
            cd /app && ls && yarn start 

  job_2:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 2
          command: |
            cd /app && ls && yarn start

  job_3:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 3
          command: |
            cd /app && ls && yarn start

  job_4:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 4
          command: |
            cd /app && ls && yarn start

  job_5:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 5
          command: |
            cd /app && ls && yarn start

  job_6:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 6
          command: |
            cd /app && ls && yarn start

  job_7:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 7
          command: |
            cd /app && ls && yarn start

  job_8:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 8
          command: |
            cd /app && ls && yarn start

  job_9:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 9
          command: |
            cd /app && ls && yarn start

  job_10:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 10
          command: |
            cd /app && ls && yarn start

  job_11:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 11
          command: |
            cd /app && ls && yarn start

  job_12:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 12
          command: |
            cd /app && ls && yarn start

  job_13:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 13
          command: |
            cd /app && ls && yarn start
  job_14:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 14
          command: |
            cd /app && ls && yarn start

  job_15:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 15
          command: |
            cd /app && ls && yarn start

  job_16:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 16
          command: |
            cd /app && ls && yarn start

  job_17:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 17
          command: |
            cd /app && ls && yarn start

  job_18:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 18
          command: |
            cd /app && ls && yarn start

  job_19:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 19
          command: |
            cd /app && ls && yarn start

  job_20:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 20
          command: |
            cd /app && ls && yarn start

  job_21:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 21
          command: |
            cd /app && ls && yarn start

  job_22:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 22
          command: |
            cd /app && ls && yarn start

  job_23:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 23
          command: |
            cd /app && ls && yarn start

  job_24:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 24
          command: |
            cd /app && ls && yarn start

  job_25:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 25
          command: |
            cd /app && ls && yarn start

  job_26:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 26
          command: |
            cd /app && ls && yarn start

  job_27:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 27
          command: |
            cd /app && ls && yarn start

  job_28:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 28
          command: |
            cd /app && ls && yarn start

  job_29:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 29
          command: |
            cd /app && ls && yarn start

  job_30:
    docker:
      - image: ngthvan1612/test-07:v5
    steps:
      - run:
          name: Job 30
          command: |
            cd /app && ls && yarn start

workflows:
  version: 2
  workflow:
    jobs:
      - job_1
      - job_2
      - job_3
      - job_4
      - job_5
      - job_6
      - job_7
      - job_8
      - job_9
      - job_10
      - job_11
      - job_12
      - job_13
      - job_14
      - job_15
      - job_16
      - job_17
      - job_18
      - job_19
      - job_20
      - job_21
      - job_22
      - job_23
      - job_24
      - job_25
      - job_26
      - job_27
      - job_28
      - job_29
      - job_30
